# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
apis/api.scouting.org/openapi.yaml:
  operation-4xx-response:
    - '#/paths/~1advancements~1awards~1{awardId}/get/responses'
    - '#/paths/~1lookups~1advancements~1activityCategories/get/responses'
    - '#/paths/~1lookups~1advancements~1activityTypes/get/responses'
    - '#/paths/~1lookups~1advancements~1calendarEventTypes/get/responses'
    - '#/paths/~1lookups~1advancements~1positions/get/responses'
    - '#/paths/~1lookups~1advancements~1swimmingClassification/get/responses'
    - '#/paths/~1lookups~1advancements~1unitTimezone/get/responses'
    - '#/paths/~1lookups~1advancements~1unitTypes/get/responses'
    - '#/paths/~1lookups~1communications~1classifications/get/responses'
    - '#/paths/~1lookups~1communications~1communicationTypes/get/responses'
    - '#/paths/~1lookups~1communications~1mobilePhoneCarrier/get/responses'
    - '#/paths/~1lookups~1communications~1phoneCountryCodes/get/responses'
    - '#/paths/~1lookups~1organizations~1types/get/responses'
    - '#/paths/~1lookups~1person~1grades/get/responses'
    - '#/paths/~1lookups~1person~1nameSuffixes/get/responses'
    - '#/paths/~1lookups~1person~1positions/get/responses'
    - '#/paths/~1lookups~1person~1titlePrefixes/get/responses'
    - '#/paths/~1lookups~1registrations~1renewalOptoutReasons/get/responses'
  rule/object-schemas-closed:
    - >-
      #/paths/~1advancements~1awards~1{awardId}/get/responses/200/content/application~1json/schema/additionalProperties
    - >-
      #/paths/~1advancements~1awards~1{awardId}~1requirements/get/responses/200/content/application~1json/schema/additionalProperties
